; Generated by scripts/generate-parsers.js. Do not edit.

[
  (first_line_silent)
  (comment_command)
] @comment

[
  (line_number_address)
  (occurrence_flag)
] @number

(last_line_address) @constant.builtin

(regex) @string.regexp

[
  (regex_beginning_anchor)
  (regex_end_anchor)
] @operator

(regex_wildcard) @character.special

[
  (regex_group_open)
  (regex_group_close)
  (regex_bracket_delimiter)
] @punctuation.bracket

[
  (regex_alternation_operator)
  (regex_zero_or_more)
  (regex_one_or_more)
  (regex_zero_or_one)
  (regex_interval)
  (regex_bracket_negation)
] @operator

[
  (regex_escape)
  (regex_quoted_escape)
  (regex_newline_escape)
  (escaped_delimiter)
  (escaped_newline)
] @string.escape

(regex_backreference) @string.special

[
  (posix_character_class)
  (collating_symbol)
  (equivalence_class)
] @character.special

(bracket_expression
  [
    (regex_bracket_literal)
    (collating_symbol)
  ] @character.special
  .
  (regex_bracket_hyphen) @character.special
  .
  [
    (regex_bracket_literal)
    (collating_symbol)
  ] @character.special)

[
  (incomplete_escape)
  (unclosed_bracket)
] @error

[
  (replacement)
  (translate_source)
  (translate_destination)
  (text_argument)
] @string

[
  (match_reference)
  (backreference)
] @string.special

(escape_sequence) @string.escape

(file_argument) @string.special
[
  (label_definition)
  (label_reference)
] @constant
(negation) @operator

(append_command
  name: (command_name) @function.builtin)
(branch_command
  name: (command_name) @function.builtin)
(change_command
  name: (command_name) @function.builtin)
(delete_command
  name: (command_name) @function.builtin)
(delete_first_line_command
  name: (command_name) @function.builtin)
(exchange_command
  name: (command_name) @function.builtin)
(get_append_command
  name: (command_name) @function.builtin)
(get_command
  name: (command_name) @function.builtin)
(hold_append_command
  name: (command_name) @function.builtin)
(hold_command
  name: (command_name) @function.builtin)
(insert_command
  name: (command_name) @function.builtin)
(label_command
  name: (command_name) @function.builtin)
(line_number_command
  name: (command_name) @function.builtin)
(list_command
  name: (command_name) @function.builtin)
(next_append_command
  name: (command_name) @function.builtin)
(next_command
  name: (command_name) @function.builtin)
(print_command
  name: (command_name) @function.builtin)
(print_first_line_command
  name: (command_name) @function.builtin)
(quit_command
  name: (command_name) @function.builtin)
(read_command
  name: (command_name) @function.builtin)
(substitute_command
  name: (command_name) @function.builtin)
(test_command
  name: (command_name) @function.builtin)
(translate_command
  name: (command_name) @function.builtin)
(write_command
  name: (command_name) @function.builtin)

(write_flag
  name: (substitute_flag_name) @function.builtin)

[
  (global_flag)
  (ignore_case_flag)
  (print_flag)
] @attribute

(block_command
  name: (command_name) @punctuation.bracket
  "}" @punctuation.bracket)

(address_range
  operator: (address_operator) @punctuation.delimiter)

((separator) @punctuation.delimiter
  (#match? @punctuation.delimiter ";"))

[
  (step_value)
  (line_offset)
  (numeric_argument)
] @number

[
  (shell_argument)
] @string

(case_conversion) @string.escape

(version_argument) @constant

[
  (multiline_flag)
  (execute_flag)
] @attribute

(clear_command
  name: (command_name) @function.builtin)
(execute_command
  name: (command_name) @function.builtin)
(file_name_command
  name: (command_name) @function.builtin)
(read_line_command
  name: (command_name) @function.builtin)
(silent_quit_command
  name: (command_name) @function.builtin)
(test_failure_command
  name: (command_name) @function.builtin)
(version_command
  name: (command_name) @function.builtin)
(write_first_line_command
  name: (command_name) @function.builtin)

(periodic_address
  operator: (address_operator) @operator)
(next_multiple_address
  operator: (address_operator) @operator)
(relative_address
  operator: (address_operator) @operator)
