/** POSIX.1-2024 sed syntax. */
module.exports = {
  commandNames: {
    label_command: ":",
    quit_command: "q",
    line_number_command: "=",
    append_command: "a",
    insert_command: "i",
    read_command: "r",
    comment_command: "#",
    delete_command: "d",
    print_command: "p",
    next_command: "n",
    delete_first_line_command: "D",
    get_command: "g",
    get_append_command: "G",
    hold_command: "h",
    hold_append_command: "H",
    next_append_command: "N",
    print_first_line_command: "P",
    exchange_command: "x",
    list_command: "l",
    block_command: "{",
    _substitute_command_without_write: "s",
    _substitute_command_with_write: "s",
    translate_command: "y",
    write_command: "w",
    branch_command: "b",
    test_command: "t",
    change_command: "c",
  },
  substituteFlags: [
    {
      rule: "occurrence_flag",
      pattern: "[[:digit:]]+",
    },
    {
      rule: "global_flag",
      spellings: ["g"],
    },
    {
      rule: "ignore_case_flag",
      spellings: ["i"],
    },
    {
      rule: "print_flag",
      spellings: ["p"],
    },
    {
      rule: "write_flag",
      spellings: ["w"],
      form: "write",
    },
  ],
  syntax: {
    extendedCommandLoopWhitespace: false,
    optionalBranchSeparator: false,
    optionalFileSeparator: false,
    trailingComment: false,
    compactBlockClose: false,
    addressRules: [
      "line_number_address",
      "last_line_address",
      "regex_address",
      "escaped_regex_address",
    ],
    commandAddressRules: ["address"],
    rangeStartRules: ["address"],
    rangeEndRules: ["address"],
    regexAddressFlags: [],
    textArgumentRules: ["_backslash_text_argument"],
    quitStatus: false,
    listWidth: false,
  },
  rules: {
    _backslash_text_argument: ($) =>
      seq(optional($._blanks), $._text_command_start, $.text_argument),
  },
  commandGroups: {
    chainable: [
      { rule: "quit_command" },
      { rule: "line_number_command" },
      { rule: "delete_command" },
      { rule: "print_command" },
      { rule: "next_command" },
      { rule: "delete_first_line_command" },
      { rule: "get_command" },
      { rule: "get_append_command" },
      { rule: "hold_command" },
      { rule: "hold_append_command" },
      { rule: "next_append_command" },
      { rule: "print_first_line_command" },
      { rule: "exchange_command" },
      { rule: "list_command" },
      { rule: "block_command" },
      {
        rule: "_substitute_command_without_write",
        alias: "substitute_command",
      },
      { rule: "translate_command" },
    ],
    line: [
      { rule: "label_command" },
      { rule: "append_command" },
      { rule: "insert_command" },
      { rule: "read_command" },
      { rule: "comment_command" },
      { rule: "write_command" },
      {
        rule: "_substitute_command_with_write",
        alias: "substitute_command",
      },
      { rule: "branch_command" },
      { rule: "test_command" },
      { rule: "change_command" },
    ],
    label: [],
  },
};
