#!/usr/bin/env node
const { spawnSync } = require("node:child_process");
const { mkdirSync, readFileSync, writeFileSync } = require("node:fs");
const { join } = require("node:path");
const { languages } = require("./variants");

const root = join(__dirname, "..");
const generatedQueryHeader =
  "; Generated by scripts/generate-parsers.js. Do not edit.\n\n";
const executable = join(
  root,
  "node_modules",
  "tree-sitter-cli",
  process.platform === "win32" ? "tree-sitter.exe" : "tree-sitter",
);

function querySource(name) {
  return readFileSync(join(root, "queries", name), "utf8").trimEnd();
}

function writeGeneratedQuery(queryDirectory, name, sections) {
  mkdirSync(queryDirectory, { recursive: true });
  writeFileSync(
    join(queryDirectory, name),
    `${generatedQueryHeader}${sections.join("\n\n")}\n`,
  );
}

function writeVariantQuery(directory, languageName, name, sections) {
  writeGeneratedQuery(join(root, directory, "queries"), name, sections);
  writeGeneratedQuery(join(root, "queries", languageName), name, sections);
}

function generateEditorQueries() {
  const commonHighlights = querySource("highlights.common.scm");
  const gnuHighlights = querySource("highlights.gnu.scm");
  const commonFolds = querySource("folds.common.scm");
  const commonIndents = querySource("indents.common.scm");
  const gnuInjections = querySource("injections.gnu.scm");

  for (const { dialect, directory, languageName } of languages) {
    writeVariantQuery(
      directory,
      languageName,
      "highlights.scm",
      dialect === "gnu"
        ? [commonHighlights, gnuHighlights]
        : [commonHighlights],
    );
    writeVariantQuery(directory, languageName, "folds.scm", [commonFolds]);
    writeVariantQuery(directory, languageName, "indents.scm", [commonIndents]);
    if (dialect === "gnu") {
      if (directory === ".") {
        writeGeneratedQuery(
          join(root, "queries", languageName),
          "injections.scm",
          [gnuInjections],
        );
      } else {
        writeVariantQuery(directory, languageName, "injections.scm", [
          gnuInjections,
        ]);
      }
    }
  }
}

function generateParsers() {
  for (const { directory } of languages) {
    const result = spawnSync(
      executable,
      [
        "generate",
        join(directory, "grammar.js"),
        "--output",
        join(directory, "src"),
      ],
      {
        cwd: root,
        stdio: "inherit",
        windowsHide: true,
      },
    );

    if (result.error) {
      if (result.error.code === "ENOENT") {
        throw new Error("Tree-sitter CLI is missing; run npm ci.", {
          cause: result.error,
        });
      }
      throw result.error;
    }

    if (result.status !== 0) {
      return result.status ?? 1;
    }
  }

  generateEditorQueries();
  return 0;
}

if (require.main === module) {
  process.exitCode = generateParsers();
}

module.exports = { generateParsers };
