name: CI

on:
  push:
    branches: [main]

permissions: read-all

jobs:
  parser:
    name: Test sed and sed_ere parsers
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - uses: tree-sitter/setup-action/cli@v2
      - run: npm ci
      - uses: tree-sitter/parser-test-action@v3
        with:
          generate: false
          test-parser-cmd: npm test

  query:
    name: Validate queries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: tree-sitter/setup-action/cli@v2
      - name: Build sed and sed_ere parsers
        run: |
          tree-sitter build --output sed.so .
          tree-sitter build --output sed_ere.so sed_ere
      - name: Set up ts_query_ls
        run: >-
          curl -fL
          https://github.com/ribru17/ts_query_ls/releases/latest/download/ts_query_ls-x86_64-unknown-linux-gnu.tar.gz
          | tar -xz
      - name: Validate sed and sed_ere queries
        run: >-
          ./ts_query_ls check -f queries/ sed_ere/queries/
          --config
          '{"parser_install_directories":["."],"language_retrieval_patterns":["(sed_ere)/queries/[^/]+\\.scm$"]}'
